config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/link_through'



  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments
    member do
      get 'like'
    end
  end
  get 'first_name', to: 'profiles#show', as: :profile
  get 'first_name/edit', to: 'profiles#edit', as: :edit_profile
  patch 'first_name/edit', to: 'profiles#update', as: :update_profile

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  post 'first_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post 'first_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'browse', to: 'articles#browse', as: :browse_articles
  # get 'profiles/show'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!
  before_action :owned_profile, only: [:edit, :update]
  before_action :set_user

  def show
    @articles = @user.articles.order('created_at DESC')
  end

  def edit

  end

  def update
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.first_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def set_user
    @user = User.find_by(first_name: params[:first_name])
  end

  def owned_profile
    @user = User.find_by(first_name: params[:first_name])
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.haml
.articles-wrapper
  .article
    .article-body
      .image-wrap
        = form_for @user, url: {action: "update"}, html: {multipart: true } do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your profile image:
                .img-circle
                  = profile_avatar_select(@user)
                = f.file_field :avatar, onChange:'loadFile(event)'
          .row
            .col-md-12
              .form-group.text-center
                %h4 Update your bio:
                = f.text_area :bio, label: false, rows: 4
          .form-group.text-center
            = f.submit "Update Profile", class: 'btn btn-success'

app/views/profiles/follow_user.js.erb
$('#follow-button').attr('class', 'btn unfollow-button').text('Following').attr('href', "/<%= @user.first_name %>/unfollow_user").attr('id', 'unfollow-button');

app/views/profiles/show.html.haml
.articles-wrapper
  .row.profile-header
    .col-md-6
      .img-circle
        = profile_avatar_select(@user)
    .col-md-6
      .first-name-and-follow
        %h3.profile-first-name
          = @user.first_name
        %span
          - if @user == current_user
            = link_to 'Edit Profile', edit_profile_path(@user.first_name), class: 'btn edit-button'
          - else
            - if current_user_is_following(current_user.id, @user.id)
              = link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post
            - else
              = link_to 'Follow', follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post
      %p.profile-bio
        = @user.bio
      .user-statistics
        %p
          = pluralize @user.articles.count, 'article'

-@articles.each do |article|
  = render 'articles/article', article: article

app/views/profiles/unfollow_user.js.erb
$('#unfollow-button').text('Follow').attr('class', 'btn follow-button').attr('href', "/<%= @user.first_name %>/follow_user").attr('id', 'follow-button');