config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/link_through'



  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments
    member do
      get 'like'
    end
  end
  get 'first_name', to: 'profiles#show', as: :profile
  get 'first_name/edit', to: 'profiles#edit', as: :edit_profile
  patch 'first_name/edit', to: 'profiles#update', as: :update_profile

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  post 'first_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post 'first_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'browse', to: 'articles#browse', as: :browse_articles
  # get 'profiles/show'
end

app/models/comment.rb
class Comment < ApplicationRecord

  #==== Associations ===================================================
  belongs_to :user, inverse_of: :comments
  belongs_to :article, inverse_of: :comments
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #==== Filters ====================================================
  before_action :set_article

  def index
    @comments = @article.comments.order("created_at ASC")
    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @comment = @article.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      create_notification @article, @comment
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = "Something went wrong, Please try again !"
      render root_path
    end
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end

  def create_notification(article)
    return if article.user.id == current_user.id
    Notification.create(user_id: article.user.id,
                        notified_by_id: current_user.id,
                        article_id: article.id,
                        comment_id: comment.id,
                        notice_type: 'comment')
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.first-name
  - if comment.user
    = link_to comment.user.first_name, profile_path(comment.user.first_name)
.comment-content
  = comment.content
  - if comment.user == current_user
    = link_to article_comment_path(article, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do
      %span(class="glyphicon glyphicon-remove delete-comment")

app/views/comments/create.js.erb
$('#comments_<%= @article.id %>').append("<%=j render 'comments/comment', article: @article, comment: @comment %>");
$('#comment_content_<%= @article.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @article.id %>').html("<%= j render @article.comments, article: @article, comment: @comment %>");

app/views/comments/index.html.haml
= render @comments, article: @article