config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'notifications/link_through'



  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments
    member do
      get 'like'
    end
  end
  get 'first_name', to: 'profiles#show', as: :profile
  get 'first_name/edit', to: 'profiles#edit', as: :edit_profile
  patch 'first_name/edit', to: 'profiles#update', as: :update_profile

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'

  post 'first_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post 'first_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'browse', to: 'articles#browse', as: :browse_articles
  # get 'profiles/show'
end

app/models/article.rb
class Article < ApplicationRecord

  #==== Image Uploader ==================================================
  has_attached_file :image, styles: {:medium => "520x"}

  #==== Associations ====================================================
  belongs_to :user, inverse_of: :articles
  has_many :comments, inverse_of: :article, dependent: :destroy
  has_many :notifications, inverse_of: :article, dependent: :destroy

  #==== Validations ====================================================
  validates :user_id, presence: true
  validates :image, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  #==== Scope ============================================================
  scope :of_followed_users, -> (following_users) { where user_id: following_users }

  acts_as_votable

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #==== Filters ====================================================
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy, :like]
  before_action :owned_article, only: [:edit, :update, :destroy]

  def index
    @articles = Article.of_followed_users(current_user.following).order('created_at DESC').page params[:page]
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = "Your article has been created."
      redirect_to articles_path
    else
      flash.now[:alert] = "Your new article has not created"
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Your article has been updated."
      redirect_to (article_path(@article))
    else
      flash.now[:alert] = "Your new article has not created"
    end
  end

  def show
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  def like
    if @article.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def browse
    @articles = Article.all.order('created_at DESC').page params[:page]
  end

  private

  def article_params
    params.require(:article).permit(:image, :caption)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def owned_article
    unless current_user == @article.user
      flash[:alert] = "That article doesn't belong to you!"
      redirect_to root_path
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def display_likes(article)
    votes = article.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
    count_likers(votes)
  end

  def likers_of(article)
    votes = article.votes_for.up.by_type(User)
    first_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        first_names.push(link_to voter.first_name, profile_path(voter.first_name), class: 'first-name')
      end
      first_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def liked_article(article)
    return 'glyphicon-heart' if current_user.voted_for? article
    'glyphicon-heart-empty'
  end

  private

  def list_likers(votes)
    first_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        first_names.push(link_to voter.first_name, profile_path(voter.first_name), class: 'first-name')
      end
      first_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end
end

app/views/articles/_article.html.haml
.articles-wrapper
  .article
    .article-head
      .thumb-img
      .first-name
        =link_to article.user.first_name, profile_path(article.user.first_name)
      .time-ago
        =time_ago_in_words article.created_at
    .image.center-block
      =link_to (image_tag article.image.url(:medium), class:'img-responsive'), article_path(article)
    .article-bottom
      = render 'articles/likes', article: article
      .caption
        .caption-content
          .first-name
            =link_to article.user.first_name, profile_path(article.user.first_name)
          =article.caption
          .comments{id: "comments_#{article.id}"}
            -if article.comments.any?
              = render article.comments.first(4), article: article
              -unless article.comments.count <= 4
                .paginator{id: "#comments-paginator-#{article.id}"}
                  =link_to "view all #{article.comments.count} comments", article_comments_path(article), remote: true, class: 'more-comments', id: "more_comments_#{article.id}", data: {article_id: "#{article.id}", type: "html", value: "#{article.comments.count}"}
    .comment-like-form.row
      .col-sm-1.like-button
        =link_to '', like_article_path(article.id), remote: true, id: "like_#{article.id}", class: "like glyphicon #{liked_article article}"
      .comment-form.col-sm-11
        =form_for([article, article.comments.build], remote: true) do |f|
          =f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{article.id}", data: { article_id: "#{article.id}", value: "#{article.comments.count}" }
          =f.submit 'New Comment', class: 'comment-submit-button'

app/views/articles/_article_dashboard.html.haml
#articles
  = render 'articles'
#paginator.text-center
  = link_to_next_page @articles, 'LOAD MORE', remote: true, id:'load_more'

app/views/articles/_article_dashboard.js.erb
$('#articles').append("<%= escape_javascript(render 'articles')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@articles, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/articles/_articles.html.haml
= render @articles

app/views/articles/_form.html.haml
.articles-wrapper
  .article
    .article-body
      .image-wrap
        = form_image_select(@article)
        = simple_form_for @article, html: { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image:
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add your caption'
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/articles/_likes.html.haml
.likes{id: "likes_#{article.id}"}
  = display_likes article

app/views/articles/browse.html.haml
= render 'article_dashboard', articles: @articles

app/views/articles/edit.html.haml
= render 'form'
.text-center.edit-links
  = link_to "Delete Article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }
  |
  = link_to "cancel", root_path

app/views/articles/index.html.haml
#articles
  = render 'articles'

#paginator.text-center
  = link_to_next_page @articles, 'LOAD MORE', remote: true, id:'load_more'

app/views/articles/index.js.erb
$('#articles').append("<%= escape_javascript(render 'articles')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@articles, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/articles/like.js.erb
$("#like_<%= @article.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#likes_<%= @article.id %>").html("<%= j (render partial: 'articles/likes', locals: { article: @article} ) %>")

app/views/articles/new.html.haml
= render 'articles/form'

app/views/articles/show.html.haml
= render 'article', article: @article
- if @article.user.id == current_user.id
  .text-center.edit-links
    = link_to "Cancel", articles_path
    |
    = link_to "Edit Article", edit_article_path(@article)
- else
  .text-center.edit-links
    =link_to "Cancel", articles_path